name: Builder

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
    
    - name: Build with Gradle
      run: ./gradlew --no-daemon clean assembleDebug testDebug

    - name: List files after build
      run: ls -R

    - name: Find build artifacts
      run: find . -type f -name "*.apk"  # Adjust if your output files have a different extension

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: "**/*.apk"  # Adjust to match your build file extension
